FROM python:3.6-buster

RUN mkdir /opt/myaicamera

RUN python -m pip install --upgrade pip

RUN python -m pip install poetry
WORKDIR /opt/myaicamera

ONBUILD COPY poetry.lock .
COPY pyproject.toml .

RUN poetry install --no-root -vvv


ENTRYPOINT ["poetry"]
