FROM python:3.6-buster

ENV http_proxy="http://proxy-web.proxy-dmz.gnc:3128"
ENV https_proxy="http://proxy-web.proxy-dmz.gnc:3128"
ENV ftp_proxy="http://proxy-web.proxy-dmz.gnc:3128"
ENV no_proxy="localhost,127.0.0.1,127.0.1.1,gitlab-infra.ref.gnc,.recif.nc,.appli-gestion.nc,.gnc,/var/run/docker.sock,10.10.106.0/24,.valid-gouv.nc,.dmz.nc,jira.gouv.nc,jira-info.gouv.nc,webnotes.gouv.nc,stats-new.gouv.nc,guichet-entreprises.nc,192.168.62.38"

RUN mkdir /opt/mycamerai

RUN python -m pip install --upgrade pip

RUN python -m pip install poetry
WORKDIR /opt/mycamerai

COPY poetry.lock .
COPY pyproject.toml .

RUN poetry install --no-root -vvv


ENTRYPOINT ["poetry"]
